version: "3.6"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=database_username
      - POSTGRES_PASSWORD=database_password
      - POSTGRES_DB=example_db_schema
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./src/config:/var/lib/postgresql/config
      - ./src/config/database/create-simple-table.sql:/docker-entrypoint-initdb.d/create-simple-table.sql